### ISSUE TITLE
Toggling cellAspect ratio destroys items and layout?

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#107]
_Commit or branch_: master

**Observed behavior:**

- Upon disabling `cellAspect` all items disappear 😱
- When activating `cellAspect: 1` again they reappear but are all positioned on top of each other 🤔
- Upon toggling of `cellAspect` all items disappear for good and never re-appear again 😞

![Feb-19-2020 17-02-59](https://user-images.githubusercontent.com/932103/74880736-d6310700-5339-11ea-86f8-021c359e041e.gif)

**Expected behavior:**

- The items should not disappear and they should also not be positioned on top of each other

**Comment by eeeeenchanted** [comment]
I think the problem is solved now.

![Feb-20-2020 17-44-30](https://user-images.githubusercontent.com/39853191/74921693-1d39fd80-5409-11ea-8d93-ecbb2e3b30dc.gif)

But if we disable both `itemSize` and `columns` then all things will disappear. I don't know whether we should fix this or not, since we said that one must provide `itemSize` or `columns`.

**Comment by flekschas** [comment]
Looks good. I think it is fine if everything disappears when `itemSize` and `columns` are `null` as this is an incorrect setting. We could, of course, disallow both from being null but that's not urgent. We should just need to make sure that when `itemSize` or `columns` is set again that the piles reappear :)

By the way, what was the issue that caused the piles to disappear permanently with the aspect ratio?

**Comment by eeeeenchanted** [comment]
Oh, it's because I didn't take care of the situation when `rowHeight` and `cellAspectRatio` are both `null`. Currently, if the grid system is incomplete, the piles would disappear for good 😂I'll try to fix this issue.

**Comment by eeeeenchanted** [comment]
I set the column number to 10 by default if both `itemSize` and `columns` are `null`, now the piles won't disappear.

![Feb-21-2020 13-04-49](https://user-images.githubusercontent.com/39853191/75006162-ca655200-54ab-11ea-9142-252839eaf8fa.gif)

Does it make sense?

**Comment by flekschas** [comment]
Yes, that sounds good :) Please either merge the fix right away or setup a PR

**Comment by eeeeenchanted** [comment]
I pushed to master already.
