### ISSUE TITLE
Move previews on hover to the top (in the z direction)

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#146]
Right now upon hovering a preview it seems like the z position is unchanged. This is a problem when setting `previewSpacing: 0` as the border is never shown.

The preview should be lifted to be "on top" of other previews similar to how a pile is always above other upon dragging.

![Mar-15-2020 18-42-43](https://user-images.githubusercontent.com/932103/76712239-1d1ddc80-66ed-11ea-9ec6-23c299a00a4a.gif)

**Comment by eeeeenchanted** [comment]
Fixed in #148
