### ISSUE TITLE
Placeholder doesn't scale with pile

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#149]
It seems like the placeholder doesn't scale with the pile. Ideally, the placeholder should scale together with the pile. Otherwise, the background difference looks a bit odd.

![Mar-15-2020 23-17-46](https://user-images.githubusercontent.com/932103/76720509-68e37c80-6713-11ea-8cf5-35ebf133add3.gif)

**Comment by eeeeenchanted** [comment]
![Mar-16-2020 12-38-40](https://user-images.githubusercontent.com/39853191/76723684-1b065d00-6783-11ea-8c25-4fe3df80291f.gif)
