### ISSUE TITLE
Test other drawing examples

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#152]
Currently, our apple example is too homogeneous, i.e., there aren't many interesting differences.

Inspired by http://formafluens.io, please test a couple of other datasets to see if we can find interesting regional clusters of differences. On their website, they highlight these differences as _diverging_ examples. Some promising datasets to test are:
- teapot (the data is already prepared)
- banana
- boomerang
- ice cream
- watermelon
- snowman

For each example please prepare the data using [`google-quickdraw-embedding.ipynb`](examples/google-quickdraw-embedding.ipynb):
1. Load the images
2. Compute their similarity
3. Compute the umap embedding based on the similarity
4. Load the images in piling.js
5. Arrange the images by the embedding
6. Cluster by overlap (maybe in combination with region) to see if there are any visible differences
7. Take a screenshot of what you found and attach :)

**Comment by eeeeenchanted** [comment]
The fish swims to different directions in different countries

<img width="886" alt="截屏2020-03-18下午6 05 15" src="https://user-images.githubusercontent.com/39853191/76949125-0cff3a80-6943-11ea-8e14-bf7e4d1cadaa.png">

**Comment by eeeeenchanted** [comment]
Power outlet in different countries

<img width="517" alt="截屏2020-03-18下午7 32 03" src="https://user-images.githubusercontent.com/39853191/76956555-39b94f00-694f-11ea-8350-dcb2a354d786.png">

**Comment by eeeeenchanted** [comment]
Bananas in different countries

<img width="822" alt="截屏2020-03-18下午9 08 17" src="https://user-images.githubusercontent.com/39853191/76963924-c7e80200-695c-11ea-88a3-12301a45c580.png">

**Comment by eeeeenchanted** [comment]
Snowman. Two snowballs in some countries and three in others.

<img width="1001" alt="截屏2020-03-18下午11 17 59" src="https://user-images.githubusercontent.com/39853191/76976544-10a8b680-696f-11ea-8b94-d8cc9594506d.png">

**Comment by eeeeenchanted** [comment]
Traffic lights. Taiwan and Japan's are horizontal

<img width="517" alt="截屏2020-03-19下午5 41 11" src="https://user-images.githubusercontent.com/39853191/77053133-d4c22f80-6a08-11ea-93c3-ee312793c54e.png">

**Comment by eeeeenchanted** [comment]
Watermelon. Slices and the whole one

<img width="683" alt="截屏2020-03-19下午5 45 30" src="https://user-images.githubusercontent.com/39853191/77053512-6f227300-6a09-11ea-9e63-72edeb3d8c05.png">

**Comment by eeeeenchanted** [comment]
Power outlet:
In North America, it's obviously two holes:
<img width="326" alt="截屏2020-03-24下午2 18 04" src="https://user-images.githubusercontent.com/39853191/77425102-2dc90380-6e0d-11ea-9d54-4ef677425fe6.png">

In East Asia & Pacific, the images are diverging:
<img width="822" alt="截屏2020-03-24下午2 18 09" src="https://user-images.githubusercontent.com/39853191/77425415-a5972e00-6e0d-11ea-91d5-eba7fd2d739a.png">

In Europe & Central Asia, mostly it's one hole:
<img width="849" alt="截屏2020-03-24下午2 18 16" src="https://user-images.githubusercontent.com/39853191/77425571-e98a3300-6e0d-11ea-975d-94d56e4e27a8.png">

**Comment by eeeeenchanted** [comment]
Snowman:
In North America, the snowman has 3 balls:
<img width="291" alt="截屏2020-03-24下午3 08 45" src="https://user-images.githubusercontent.com/39853191/77425767-34a44600-6e0e-11ea-84e1-58b50906281e.png">
In East Asia & Pacific, many countries' snowmen have 2 balls:
<img width="735" alt="截屏2020-03-24下午3 09 26" src="https://user-images.githubusercontent.com/39853191/77425905-6cab8900-6e0e-11ea-95a4-65d2deb4f7f2.png">
In Europe & Central Asia, it's also 3 balls:
<img width="682" alt="截屏2020-03-24下午3 08 59" src="https://user-images.githubusercontent.com/39853191/77426069-b5fbd880-6e0e-11ea-9717-316a46278516.png">

**Comment by flekschas** [comment]
Closing this as we've tested a bunch now :)
