### ISSUE TITLE
Content Awareness in a File System Interface: Implementing the 'Pile' Metaphor for Organizing Information

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#16]
**Rose et al., 1993, doi: https://doi.org/10.1145/160688.160735**

**Goals of the paper:**
An interface design based on the pile concept suggested uses of content awareness for describing, organizing, and filing textual documents. 

<img width="610" alt="屏幕快照 2019-07-30 上午11 39 03" src="https://user-images.githubusercontent.com/39853191/62143865-d0e96d80-b2be-11e9-87ed-4eb0bc600690.png">

**High-level tasks:**
- Keyword extraction / summarization
- Automatic organization (sub-piling)
- Automatic filing (select the best-matching pile)
- Sorting

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
