### ISSUE TITLE
Pile size badge's position is not correct

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#163]
In the matrix example, the badge will be positioned at the center of the cover:

<img width="120" alt="截屏2020-03-23上午11 11 26" src="https://user-images.githubusercontent.com/39853191/77291841-f6c5f580-6d19-11ea-9945-25e8ff81c211.png">

In the joy-plot example, if I set `pileSizeBadgeAlign` to `['bottom', 'right']`, the position is also incorrect:

<img width="149" alt="截屏2020-03-23上午11 32 05" src="https://user-images.githubusercontent.com/39853191/77291896-14935a80-6d1a-11ea-958f-3cd776e92388.png">

**Comment by flekschas** [comment]
Fixed in 65d24bc65198267aa88370a4f77d1340ade2c59e
