### ISSUE TITLE
The pile background is not properly updated upo

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#165]
After deactivating pile labels the size of the background is not updated properly:

![Mar-25-2020 09-23-29](https://user-images.githubusercontent.com/932103/77548706-470d9680-6e85-11ea-8c3d-d7d43be2d310.gif)

I think we just need to call `drawBorder` again as the background is correct after mousing over the piles

**Comment by eeeeenchanted** [comment]
Fixed in 971762e624e2e1c84f1e9576c0b09c58f0f82aae
