### ISSUE TITLE
Computationally-Enriched 'Piles' for Managing Digital Photo Collections

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#17]
**Bauer et al., 2004, doi: https://doi.org/10.1109/VLHCC.2004.13**

**Goals of the paper:**
Dynapad lets users explore and organize collections of digital photos and other media, using “computationally-enriched piles”, portable areas of customizable automation, to create and manage diverse, changing, and opportunistic arrangements.

<img width="497" alt="屏幕快照 2019-07-30 上午11 43 24" src="https://user-images.githubusercontent.com/39853191/62144120-42c1b700-b2bf-11e9-95e2-1c48289a7598.png">

**High-level tasks:**
- Organize collections of images
- Explore collections
- Sorting

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
