### ISSUE TITLE
Social navigation as a model for usable security

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#18]
**DiGioia et al, 2005, doi: https://doi.org/10.1145/1073001.1073011**

**Goals of the paper:**
Use pile metaphor to support social navigation, producing a dynamic information space within which a user has a new form of control over the shared media, and makes sharing decisions based on social navigation cues.

<img width="594" alt="屏幕快照 2019-07-30 上午11 55 55" src="https://user-images.githubusercontent.com/39853191/62145214-01caa200-b2c1-11e9-996a-1f9a91f87196.png">

**High-level tasks:**
- Quick overview of the files
- Support social navigation
- Summarization / keyword extraction
- Sharing

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
