### ISSUE TITLE
Temp depile border is not correct

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#182]
_Commit or branch_: select-to-pile

#### Observed behavior

- The temp depile border isn't correct after I close temp depile. 

![Apr-01-2020 16-17-28](https://user-images.githubusercontent.com/39853191/78148274-41a4e300-7467-11ea-87f8-857abee2f9d3.gif)

#### Expected behavior

- The border should go back to normal after closing temp depile

**Comment by flekschas** [comment]
Oh I might know what causes this
