### ISSUE TITLE
Spatial Tools for Managing Personal Information Collections

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#19]
**Bauer et al, 2005, doi: https://doi.org/10.1109/HICSS.2005.551**

**Goals of the paper:**
The research objective is to explore a generalization of the notion of a “pile” as a foundation for a versatile suite of tools to provide unobtrusive assistance for organizing collections and other sensemaking activities.

<img width="524" alt="屏幕快照 2019-07-30 上午11 58 31" src="https://user-images.githubusercontent.com/39853191/62145383-5d952b00-b2c1-11e9-8bff-da45d47104b1.png">

**High-level tasks:**
- Organization of collections of data

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
