### ISSUE TITLE
Entangle updateCover and updatePreviewStyle

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#195]
After some recent refactoring, we now have a `updateCover()` function but this function is calling 
`updatePreviewStyle()` which is a little bit confusing because the preview styles should also be updated even when there is no cover.

**Comment by eeeeenchanted** [comment]
Hi Fritz, I'm not sure what should I do here. Should I separate `updatePreviewStyle()` from `uppdateCover()`?

**Comment by flekschas** [comment]
Yep :) This is not an important issue, I just recently played with previews and *no* cover and was looking for the code that was updating the style of the preview. it took me a little bit to find it because the function is bound to `updateCover`, which is a bit confusing as I didn't have a cover.

So the goal is to separate `updatePreviewStyle()` from `updateCover()` as the two should really be independent. If there is some logic combining the two we could maybe introduce a new function called `updatePreviewsAndCover` which then calls `updateCover` and `updatePreviewStyle` if necessary
