### ISSUE TITLE
Item position is not correct when updating layout

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#196]
As the title said

![Apr-21-2020 12-15-12](https://user-images.githubusercontent.com/39853191/79825153-d0ec4900-83ca-11ea-9b37-0886528e3feb.gif)

The issue is introduced in https://github.com/flekschas/piling.js/commit/bfbe4b6163a80ad15de2f783331dc6f4b2d89ae9

**Comment by flekschas** [comment]
Are you referring to the cell alignment?
