### ISSUE TITLE
BumpTop: Keepin' it real: pushing the desktop metaphor with physics, piles and the pen

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#20]
**Agarawala and Balakrishnan, 2006, doi: https://doi.org/10.1145/1124772.1124965**
URL: https://bumptop.github.io/

**Goals of the paper:**
We explore making virtual desktops behave in a more physically realistic manner by adding physics simulation and using piling instead of filing as the fundamental organizational structure. 

<img width="496" alt="屏幕快照 2019-07-30 下午12 00 42" src="https://user-images.githubusercontent.com/39853191/62145571-b369d300-b2c1-11e9-876e-f4b1b7a59676.png">
<img width="495" alt="屏幕快照 2019-07-30 下午12 00 53" src="https://user-images.githubusercontent.com/39853191/62145572-b369d300-b2c1-11e9-9337-6310ad870c8d.png">

**High-level tasks:**
- Casual organization of documents
- Manipulating and organizing piles
- Rearrangement

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
