### ISSUE TITLE
On temp depile: adjust opacity of entire pile, individual items

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#204]
It looks cool but I don't think it's useful as faded-out piles with large numbers of items are just too noticeable:

<img width="505" alt="Screen Shot 2020-04-26 at 5 26 58 PM" src="https://user-images.githubusercontent.com/932103/80320236-4305c900-87e3-11ea-86ec-7b3771e36bda.png">

**Comment by eeeeenchanted** [comment]
I'm sorry, but do you mean to adjust the opacity of the pile or individual items or both? Right now I'm adjusting the opacity of the pile's `rootContainer`, see https://github.com/flekschas/piling.js/blob/master/src/library.js#L3746.

**Comment by flekschas** [comment]
Interesting. Maybe I caused the visual change by replacing the graphics element with a container 🤔 Can you do a quick test to see if changing the root container back to a graphics object would change the visual output?

Essentially, instead of having the opacity of every individual item adjusted, the opacity of the pile as a whole should change.

**Comment by eeeeenchanted** [comment]
No, the issue still exists. Actually I think the issue existed all the time.

I found this issue on pixi's github that might be related: https://github.com/pixijs/pixi.js/issues/4334

**Comment by flekschas** [comment]
I think there's a very easy workaround:

1. Add dispersed pile to a separate container that sits on top of normal piles (can we use `activePile`?)
2. Add a container in between normal piles and the dispersed pile with a single black sprite texture. Set the transparency of that texture to 0.66 or somethings

To get a black sprite do

```javascript
const blackSprite = new PIXI.Sprite(PIXI.Texture.WHITE);
blackSprite.tint = 0x000000;
blackSprite.width = containerWidth;
blackSprite.height = containerHeight;
```
