### ISSUE TITLE
Interacting with piles of artifacts on digital tables

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#21]
**Aliakseyeu et al., 2006, doi: https://doi.org/10.1145/1133265.1133298**

**Goals of the paper:**
Investigate how users should interact with digital piles

<img width="618" alt="屏幕快照 2019-07-30 下午12 03 04" src="https://user-images.githubusercontent.com/39853191/62145761-004da980-b2c2-11e9-88db-9ba621980809.png">

**High-level tasks:**
- Navigation
- Reorganization between piles
- Reposition within piles

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
