### ISSUE TITLE
Bubble clusters: an interface for manipulating spatial aggregation of graphical objects

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#22]
**Watanabe et al., 2007, doi: https://doi.org/10.1145/1294211.1294241**

**Goals of the paper:**
We propose an interface for manipulating spatial aggregations of objects. The aggregated objects are automatically recognized as a group, and the group structure is visualized as a two-dimensional bubble surface that surrounds the objects.

<img width="597" alt="屏幕快照 2019-07-30 下午12 04 39" src="https://user-images.githubusercontent.com/39853191/62145880-3a1eb000-b2c2-11e9-8127-2772f3d04d1a.png">

**High-level tasks:**
- Recognize aggregated objects as a group
- Automatic update the group structure
- Expand the group
- Reorganization

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
