### ISSUE TITLE
Piles, tabs and overlaps in navigation among documents

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#23]
**Jakobsen et al., 2010, doi: https://doi.org/10.1145/1868914.1868945**

**Goals of the paper:**
We explore variations on navigation support: arranging documents with tabs, as overlapping windows, and in piles.

<img width="560" alt="屏幕快照 2019-07-30 下午12 06 54" src="https://user-images.githubusercontent.com/39853191/62146036-8964e080-b2c2-11e9-9702-dc01e93dd154.png">

**High-level tasks:**
- Document navigation
- Spatially arrange documents
- Automatic layout
- Ordering

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
