### ISSUE TITLE
Interaction techniques for hybrid piles of documents on interactive tabletops

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#24]
**Khalilbeigi et al., 2010, doi: https://doi.org/10.1145/1753846.1754083**

**Goals of the paper:**
We contribute several techniques for interacting with hybrid piles of printed and digital documents on tabletops. By employing a soap bubble metaphor and by using paper as a tangible control for the hybrid pile, these allow easy creating and rearranging piles while maintaining the flexibility of traditional paper piles.

<img width="621" alt="屏幕快照 2019-07-30 下午12 08 22" src="https://user-images.githubusercontent.com/39853191/62146129-bd400600-b2c2-11e9-8982-2176ceed39d2.png">

**High-level tasks:**
- Organizing documents
- Rearranging piles
- Navigation

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
