### ISSUE TITLE
DisplayStacks: interaction techniques for stacks of flexible thin-film displays

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#25]
**Girouard et al, 2012, doi: https://doi.org/10.1145/2207676.2208406**

**Goals of the paper:**
Stacking physical documents is one of the main forms of spatio-temporal organization of information. We present DisplayStacks, a system that enables physical stacking of digital documents via piles of flexible E Ink displays.

<img width="597" alt="屏幕快照 2019-07-30 下午12 10 18" src="https://user-images.githubusercontent.com/39853191/62146262-02fcce80-b2c3-11e9-9699-c8a2511a064f.png">

**High-level tasks:**
- Organization of information
- Rearrange document
- Sorting 
- Summarizing

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
