### ISSUE TITLE
OnSet: A Visualization Technique for Large-scale Binary Set Data

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#26]
**Sadana et al., 2014, doi: https://doi.org/10.1109/TVCG.2014.2346249**

**Goals of the paper:**
We present OnSet, an interactive, scalable visualization technique for representing large-scale binary set data.

<img width="565" alt="屏幕快照 2019-07-30 下午12 11 51" src="https://user-images.githubusercontent.com/39853191/62146355-3a6b7b00-b2c3-11e9-881d-b4976d6fe94f.png">

**High-level tasks:**
- Direct manipulation
- Explore collections
- Ordering

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
