### ISSUE TITLE
Small MultiPiles: Piling Time to Explore Temporal Patterns in Dynamic Networks

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#28]
**Bach et al., 2015, doi: https://doi.org/10.1111/cgf.12615**

**Goals of the paper:**
Explore time-series of dynamics, weighted networks with a sequence of hundreds of temporal samples (snapshots)

<img width="558" alt="屏幕快照 2019-07-30 下午12 14 55" src="https://user-images.githubusercontent.com/39853191/62146567-a817a700-b2c3-11e9-9b98-cd760aee502a.png">

**High-level tasks:**
- organize data
- explore groups (states) and individuals
- see trends/changes
- summarize groups

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
