### ISSUE TITLE
Visualizing Dynamic Hierarchies in Graph Sequences

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#29]
**Vehlow et al., 2016, doi: https://doi.org/10.1109/TVCG.2015.2507595**

**Goals of the paper:**
We developed a visualization technique that supports the analysis of the topology and the hierarchical group structure of a dynamic graph and the tracking of changes over time.

<img width="621" alt="屏幕快照 2019-07-30 下午12 16 30" src="https://user-images.githubusercontent.com/39853191/62146677-e0b78080-b2c3-11e9-8436-f24f1604eecc.png">

**High-level tasks:**
- Explore: see trends/changes
- Sorting

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
