### ISSUE TITLE
HiPiler: Visual Exploration of Large Genome Interaction Matrices with Interactive Small Multiples

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#30]
**Lekschas et al., 2017, doi: https://doi.org/10.1109/TVCG.2017.2745978**

**Goals of the paper:**
This paper presents an interactive visualization interface—HiPiler—for the exploration and visualization of regions-of-interest in large genome interaction matrices.

<img width="627" alt="屏幕快照 2019-07-30 下午12 18 07" src="https://user-images.githubusercontent.com/39853191/62146800-1bb9b400-b2c4-11e9-81af-63de8ee7c2b3.png">

**High-level tasks:**
- Explore
- Filtering
- Summarization
- Locating

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
