### ISSUE TITLE
BayesPiles: Visualisation Support for Bayesian Network Structure Learning

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#31]
**Vogogias et al., 2018, doi: https://doi.org/10.1145/3230623**

**Goals of the paper:**
We address the problem of exploring, combining, and comparing large collections of scored, directed networks for understanding inferred Bayesian networks used in biology.

<img width="626" alt="屏幕快照 2019-07-30 下午12 19 41" src="https://user-images.githubusercontent.com/39853191/62146885-53286080-b2c4-11e9-9b89-b9105040ac04.png">

**High-level tasks:**
- Explore
- Ordering
- Filtering
- Summarizing

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
