### ISSUE TITLE
A domain-specific language to visualize software evolution

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#32]
**Fernandez and Bergel, 2018, doi: https://doi.org/10.1016/j.infsof.2018.01.005**

**Goals of the paper:**
This paper explores the use of stacked adjacency matrices and a domain specific language to produce tailored interactive visualizations for software evolution exploration.

<img width="367" alt="屏幕快照 2019-07-30 下午12 21 45" src="https://user-images.githubusercontent.com/39853191/62147038-ab5f6280-b2c4-11e9-8350-6c9768a1b483.png">

**High-level tasks:**
- Summarization
- Filtering
- Locating

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
