### ISSUE TITLE
Pattern-Driven Navigation in 2D Multiscale Visualizations with Scalable Insets

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#33]
**Lekschas et al., 2019, doi: https://doi.org/10.1101/301036**

**Goals of the paper:**
We present Scalable Insets, a technique for interactively exploring and navigating large numbers of annotated patterns in multiscale visual spaces such as gigapixel images, matrices, or maps. 

<img width="603" alt="屏幕快照 2019-07-30 下午12 23 14" src="https://user-images.githubusercontent.com/39853191/62147102-d21d9900-b2c4-11e9-84f0-d795ecede9c2.png">

**High-level tasks:**
- Explore
- Summarization

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
