### ISSUE TITLE
How Do People Organize Their Desks? Implications for the Design of Office Information Systems

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#34]
**Thomas W. Malone, 1983, doi: https://doi.org/10.1145/357423.357430**

<img width="428" alt="屏幕快照 2019-08-02 下午12 02 40" src="https://user-images.githubusercontent.com/39853191/62383336-83b70700-b51d-11e9-9e4c-0cee987a7fce.png">

**Comment by flekschas** [comment]
Closed. (This was use for the literature review)
