### ISSUE TITLE
The grid resets when setting another property afterward

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#35]
E.g., 

```
  piling.set('renderer', svgRenderer);
  piling.set('items', data);
  piling.set('itemAlignment', ['top', 'bottom', 'left', 'right']);
  piling.set('grid', [10]);
```

![Screen Shot 2019-10-29 at 1 50 44 PM](https://user-images.githubusercontent.com/932103/67794544-30d4e900-fa53-11e9-8f5c-4df1ccbbf274.png)

works as expected but 

```
  piling.set('renderer', svgRenderer);
  piling.set('items', data);
  piling.set('grid', [10]);
  piling.set('itemAlignment', ['top', 'bottom', 'left', 'right']);
```

![Screen Shot 2019-10-29 at 1 50 55 PM](https://user-images.githubusercontent.com/932103/67794518-287cae00-fa53-11e9-82d3-3e5ee9d9855c.png)

fails.

**Comment by eeeeenchanted** [comment]
Fixed in this commit [b01c8f3](https://github.com/flekschas/piling.js/commit/b01c8f33f172ff80fb3fe023c9d566f8fbd77258)
