### ISSUE TITLE
Define and implement public event API

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#43]
To make the lives of other developers easier and provide hooks for integrating piling.js into their applications we should implement well-defined public events. This document is meant as a working sheet to flash out which events we want to support.

Global events:
1. `init` should fire after piling.js has been properly initialized and is ready to be used
   Return: _nothing_
2. `change` should fire whenever the state of piling.js has changed
   Return: Maybe the event that caused the change
3. `render` should fire whenever data has been rendered
   Return: _nothing_

Specific events:
1. `pileSelect` should fire when the user selects a pile
   Return: the pile definition and original event object
2. `pileFocus` should fire when the user focuses a pile
   Return: the pile definition and original event object
3. `pileActive` should fire when the user actively browses a pile, i.e., through temporary de-piling
   Return: the pile definition and original event object
4. `pileLiveRendering` should fire when the switches to live rendering (this state isn't implemented yet)
   Return: the pile definition and original event object
5. `pileEnter` should fire when the mouse cursor hovers over a pile
   Return: the pile definition and original event object
6. `pileLeave` should fire when the mouse cursor leaves a pile
   Return: the pile definition and original event object

Custom context menu events:
The user should be able to define custom context menu items that trigger an event called `pileCustom` that returns custom event type and the pile definition. (We have to refactor how custom events are supported first but just for the sake of documentation I am describing it here)

**Comment by eeeeenchanted** [comment]
Hi Fritz, what is the original event object?

**Comment by flekschas** [comment]
The event object that one receives from an event callback. Eg element.addEventListener(‘click’, function(event) { console.log(‘I am the event object’, event); })
    	
    	

    	
    
  




On Tue, Dec 17, 2019 at 5:12 AM +0100, "eeeeenchanted" <notifications@github.com> wrote:












Hi Fritz, what is the original event object?

**Comment by flekschas** [comment]
Implemented in #52
