### ISSUE TITLE
Allow customizing the style of piles and items dynamically

### ISSUE THREAD

**Issue by eeeeenchanted** [flekschas/piling.js#53]
Like in D3 there should be a function, e.g., `item(property, callback)`, that allows setting specific style properties of items. The callback should receive the item data and the pile data.
- Opacity
- Scale
- Border styling

**Comment by eeeeenchanted** [comment]
Hi Fritz, I assume that the user will return the item data, pile data, and the value to be set to the property in their callback function, then in the library, we receive this data and dynamically change the style of the item. Is my understanding correct?

**Comment by flekschas** [comment]
Yes it is!
The signature of the callback function should be as follows:
```
function (itemInstance, pileInstance, itemPosition) {
  // Do some stuff
  return value;
}
```
Where `itemInstance` is the instance of the item, `pileInstance` is the instance of the pile that this item is part of, and `itemPosition` is the position of the item on the pile. This function should then  return the value corresponding to the property, e.g., if we have `item('opacity', handleItemOpacity)` then `handleItemOpacity` should return a float value in `[0,1]` which acts as the opacity of the item.

**Comment by eeeeenchanted** [comment]
In this case, the library should provide the information about `itemInstance`, `pileInstance` and `itemPosition` right? Then how can we know which item the user wants to change?

**Comment by flekschas** [comment]
That's right, the library has to pass those arguments to the callback function.

The library doesn't need to know anything about what will happen. All it needs to do is check if the user has specified a function and then call it.

E.g., below I fleshed out the basic structure. Variable names etc. might be different.

```
// A utils function
const isFunction =(obj) => !!(obj && obj.constructor && obj.call && obj.apply);

// This needs to be called where the piles are updated
piles.forEach(pile => {
  pile.items.forEach((item, i) => {
    if (isFunction(state.itemOpacity)) {
      item.opacity = state.itemOpacity(item, pile, i);
    }
  });
});
```

I just realized that we shouldn't call the function to define the styling `item` because the _scale_ and _border size_ is applied to the entire pile and not the pile items. Maybe we can call it `style` and call the properties:
- `itemOpacity`
- `pileOpacity`
- `pileScale`
- `pileBorderSize`

(We can add `pileOpacity` later)

**Comment by eeeeenchanted** [comment]
So these 4 properties should be the properties in the redux store? If the user defines a function, then in the `style` function, we set the property in the store to this function, and in the `update` function, we update the piles accordingly. Is this process correct?

**Comment by flekschas** [comment]
Yep, that sounds good.

One small addition, we should probably also support static values for the 4 properties. To support this we just have to change:
```
if (isFunction(state.itemOpacity)) {
  item.opacity = state.itemOpacity(item, pile, i);
}
```
to
```
if (state.itemOpacity !== null) {
  item.opacity = isFunction(state.itemOpacity)
    ? state.itemOpacity(item, pile, i)
    : state.itemOpacity;
}
```
