### ISSUE TITLE
Grid lines incomplete

### ISSUE THREAD

**Issue by flekschas** [flekschas/piling.js#60]
_Commit or branch_: master

#### Observed behavior
1. The grid is only drawn for rows that contain piles
2. The left-most and top-most grid lines are drawn

#### Expected behavior
1. If there is more available space the grid should be drawn across the entire container
2. The left-most and top-most grid lines should not be drawn

**Why?** If space is available, one might want to be guided by the grid for dragging piles.

#### Steps to reproduce
1. Limit the number of piles to 10
2. View piling.js on a large screen
3. Right-click then show grid

**Example:**
<img width="833" alt="Screen Shot 2020-01-07 at 11 58 13 PM" src="https://user-images.githubusercontent.com/932103/71992837-11e99480-3204-11ea-9378-da455efa3d75.png">

1. In the screenshot above the grid should be extended till the end of the container.
2. The top-most and left-most grid line is unnecessary and looks a bit odd.

**Comment by flekschas** [comment]
The new grid lines are better but still incomplete :)

![Screen Shot 2020-01-09 at 11 40 04 AM](https://user-images.githubusercontent.com/932103/72086672-4d07c880-32d5-11ea-9993-c31128fa5cdf.png)

Also, could you remove the last vertical line? I think it looks nicer when only the _inner_ lines of the grid are shown.

**Comment by eeeeenchanted** [comment]
Can you test if the grid lines are complete now?

**Comment by flekschas** [comment]
Good job! Looks good now
